-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "2560x1440@239.992", position = "2560x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "2560x1440@164.958", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-3", mode = "2560x1440@239.992", position = "5120x0", scale = 1, vrr = 0 })
